#!/bin/sh
set -e
mount none /sys/kernel/config -t configfs
cd /sys/kernel/config/usb_gadget
mkdir g1
cd g1
mkdir configs/c.1
mkdir functions/midi.usb0
mkdir strings/0x409
mkdir configs/c.1/strings/0x409
echo 4096 > functions/midi.usb0/buflen
echo 0x0004 > idProduct
echo 0x17b3 > idVendor
echo "MIDI function" > strings/0x409/product
echo "Conf 1" > configs/c.1/strings/0x409/configuration
ln -s functions/midi.usb0 configs/c.1
echo "ci_hdrc.0" > UDC
